name: management-system

services:
  backend:
    image: ${DOCKER_USERNAME:-local}/managementsystem-backend:latest
    build:
      context: ./BackEnd
      dockerfile: dockerfile
    container_name: management-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      DB_HOST: mysql-klinik
      DB_PORT: "3306"
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    networks:
      - klinik-network

  frontend:
    image: ${DOCKER_USERNAME:-local}/managementsystem-frontend:latest
    build:
      context: ./FrontEnd/my-app
      dockerfile: dockerfile
      args:
        NEXT_PUBLIC_API_URL: "https://api-manajemen.kriampelgading.my.id"
    container_name: management-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - klinik-network

networks:
  klinik-network:
    external: true