name: CD

on:
  workflow_run:
    workflows: ["CI"]   # Harus sama dengan "name" pada ci.yml
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Ubuntu Server

    # Deploy hanya jika CI berhasil
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (
        github.event.workflow_run.head_branch == 'main' ||
        github.event.workflow_run.head_branch == 'develop' ||
        github.event.workflow_run.head_branch == 'Development'
      )

    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            echo "===== DEPLOY START ====="

            cd ${{ secrets.PROJECT_PATH }}

            echo "Current Directory:"
            pwd

            echo "Checkout Branch"
            git checkout ${{ github.event.workflow_run.head_branch }}

            echo "Pull Latest Source"
            git pull origin ${{ github.event.workflow_run.head_branch }}

            echo "Stopping Containers..."
            docker compose down

            echo "Building Containers..."
            docker compose build --no-cache

            echo "Starting Containers..."
            docker compose up -d

            echo "Removing Unused Images..."
            docker image prune -f

            echo "Running Containers:"
            docker ps

            echo "===== DEPLOY FINISHED ====="